replicaCount: 1
image:
 repository: harbor.corp.example.com/ibm-mq
 tag: "9.3.2"
 pullPolicy: IfNotPresent
resources:
 limits:
   cpu: "500m"
   memory: "1Gi"
 requests:
   cpu: "250m"
   memory: "512Mi"
service:
 type: ClusterIP
