apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
 name: {{ .Values.secretProviderClass }}
spec:
 provider: gcp
 parameters:
   secrets: |
     - resourceName: "projects/YOUR_PROJECT_ID/secrets/mq-key-kdb"
       fileName: "key.kdb"
     - resourceName: "projects/YOUR_PROJECT_ID/secrets/mq-key-rdb"
       fileName: "key.rdb"
     - resourceName: "projects/YOUR_PROJECT_ID/secrets/ltpa-keys"
       fileName: "ltpa.keys"
     - resourceName: "projects/YOUR_PROJECT_ID/secrets/mqwebuser"
       fileName: "mqwebuser.xml"
