apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: iib-mq
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/jpdevops341/devops-gitops-iib-mq-ace.git
   targetRevision: HEAD
   path: helm-charts/iib-mq
 destination:
   server: https://kubernetes.default.svc
   namespace: iib-mq
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
     - CreateNamespace=true
